language: php

php: 
  - 5.3
before_script: 
  - mkdir -p shippable/codecoverage
  - mkdir -p shippable/testresults
script:
  - phpunit calculator_test.php --with-junit --junit-file=shippable/testresults/phpunit.xml
  - coverage run --branch calculator_test.php
  - coverage xml -o shippable/codecoverage/coverage.xml calculator_test.php
  
notifications:
   email: false


      
