language: php

php: 
  - 5.3
before_script: mkdir -p shippable/codecoverage
script:
  - phpunit calculator_test.php --with-junit --junit-file=shippable/testresults/phpunit.xml
  - --log-junit calculator_test.php
  - coverage xml -o shippable/codecoverage/coverage.xml calculator_test.php		
notifications:
   email: false


      
